version: "3"

services:
  fastapi:
    container_name: "fastapi"
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app/src:/app
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Tokyo
