version: "3.9"

services:

  api:
    container_name: "fastapi"
    depends_on:
      - db
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app/app
      - ./db:/usr/src/app/db
      - ./scripts:/usr/src/app/scripts
        #working_dir: /usr/src/app/scripts
        #command: bash -c "./run.sh" #alembicでコンテナ立ち上げ時にmigrationするなら使う
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development

  db:
    container_name: "mysql"
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    platform: linux/x86_64
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env.development

  react:
    container_name: "front"
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    volumes:
      - ./front/src:/usr/src/front/src
      - ./front/public:/usr/src/front/public
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env.development
    links:
      - db
    ports:
      - 4000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

volumes:
  db-data: #コンテナのvolumeを使って永続化
      
