version: "3"

services:

  api:
    container_name: "fastapi_starter"
    depends_on:
      - db
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app/app
      - ./db:/usr/src/app/db
      - ./scripts:/usr/src/app/scripts
    working_dir: /usr/src/app/scripts
    command: bash -c "./run.sh"
    networks:
      - fastapi_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development

  db:
    container_name: "fastapi_starter_db"
    platform: linux/arm64/v8
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    restart: always
    tty: true
    expose:
      - "3306"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
    networks:
      - fastapi_network
    ports:
      - 3306:3306
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.development

        #  react:
        #    container_name: "front"
        #    build:
        #      context: ./docker/front
        #      dockerfile: Dockerfile
        #    volumes:
        #      - ./front/src:/app/front/src
        #      - ./front/public:/app/front/public
        #    ports:
        #      - 3000:3000
        #    tty: true
        #    stdin_open: true

networks:
  default:
    external:
      name: bridge
  fastapi_network:
    name: fastapi_network
    driver: bridge
    external: true

      #volumes:
      #  db-data: #コンテナのvolumeを使って永続化
