"""empty message

Revision ID: 2425fb2e1891
Revises: 
Create Date: 2023-02-22 11:38:09.565196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '2425fb2e1891'
down_revision = 'f85acc9d4850'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    view_query = "CREATE VIEW answer_rate_view AS SELECT card_id, user_id, AVG(judgement) AS answer_rate FROM record_details GROUP BY card_id, user_id"
    conn.execute(text(view_query))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
