"""empty message

Revision ID: 859ba77eff45
Revises: a650c944b5aa
Create Date: 2023-02-21 01:23:56.179441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859ba77eff45'
down_revision = 'a650c944b5aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
