"""empty message

Revision ID: a650c944b5aa
Revises: 
Create Date: 2023-02-21 00:58:03.808707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a650c944b5aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    #conn = op.get_bind()
    #conn.execute("CREATE VIEW answer_rate_view AS SELECT card_id, user_id, AVG(judgement) AS answer_rate FROM record_details GROUP BY card_id, user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
