"""empty message

Revision ID: f219cc254ef8
Revises: 7a4f5491d26b
Create Date: 2023-02-18 21:15:14.387798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f219cc254ef8'
down_revision = '7a4f5491d26b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=65535), nullable=True))
    op.drop_column('users', 'reflesh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reflesh_token', mysql.MEDIUMTEXT(collation='utf8mb4_bin'), nullable=True))
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
